version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    commit-message:
      prefix: "Deps"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"
