version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Deps"
