name: Build the Greenbone Documentation

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-docs:
    name: Cleanup CI build
    runs-on: 'ubuntu-latest'
    env:
      DOC_ROOT: pr/${{ github.head_ref }}
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "gh-pages"
      - name: Test Document Root Exists
        id: doc-root
        run: |
          echo "Checking if $DOC_ROOT exists"
          if [ -d "$DOC_ROOT" ]; then
            echo "has-doc-root=true" >> $GITHUB_OUTPUT
          else
            echo "has-doc-root=false" >> $GITHUB_OUTPUT
          fi
      - name:  Cleanup Document Root and Update GitHub Pages
        if: steps.doc-root.outputs.has-doc-root == 'true'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git rm -r "$DOC_ROOT"
          git commit --amend -m "Updating Docs for commit ${GITHUB_SHA} (PR Cleanup)"
          git push --force-with-lease
      - name: Upload pages artifact
        if: steps.doc-root.outputs.has-doc-root == 'true'
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - name: Deploy to GitHub Pages
        if: steps.doc-root.outputs.has-doc-root == 'true'
        uses: actions/deploy-pages@v2
