name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 'Dependency Review'
        uses: greenbone/actions/dependency-review@v3
